language: minimal
services: 
  - docker
script:
  - bash build-docker.sh
deploy: 
  provider: s3
  # travis-rock-deployer
  access_key_id: AKIAITCXLO3P634Q6U7A
  secret_access_key:
    secure: "ssYG4pSm/WznXgU0TUmMW7a+6w8+wxSJXxS1pcv/tpA9O/F8ksaPZhJhpVvRs+RxMQCmE3y8mw+shTSyktZxK7SGH6oBhemVL1ZfTf8o9L9uMLwKDmR0YkyZwPKs6qRZpC1HtfWGKT6H5Ms+irbDuzrHS1cJCaQGXrCQHuB0YqkpcrNs985YIq6RFZ/DW+EfI5ghltk528oHXdbo1DmVyhcBGIFcAOkAgsOcLxK1t+YFbFoWmAhCsI+LFME+3X3NwMdrR5HhHio6sc7QAMDFpZZ1ft2Kw8RIX2LB/VVGq8RD1YYH06874LGnj3zkZwpLWKbg5W8MVENhRV4fFdQJ80dF807pFGRevaxDj7Qn+ISBRetxZs/KwY9G2Fsayyt6N2DaBxXmWZZtacVsOrHHQBB6LxQiAZMKLCP4navDsZdISt906uuJqN0xIRJuApm03ZC8liYUITHmQFX6vlsrFPmmuiEsi0hClIWtoqynTkcUQaAr39AqIWeFQ19/TDCzHpna1MqZ2UlqogAWr9yKs7aQ8kd3WNrSTq5+MmhJmks3y9FP7VlJcSubmQu4R3QjaX42J3TtIWxfGDbEsiljUahDoU5ltKJhGCbnALyg9BqMZs9ZyFSomeSi6eJVQJzG9gZQ1esQLnO0w0Jb3c8sjJTdzVqKyXsmPeEsjiE32uA="
  bucket: aws-website-stage-rpfg4
  upload-dir: stats
  local_dir: dist
  skip_cleanup: true
  region: us-east-1
  on:
    branch: master
  
